### ISSUE TITLE
Thank you very much for this: Tip for PHP Intelephense

### ISSUE THREAD

**Issue by swashata** [GiacoCorsiglia/wordpress-stubs#1]
First of all, thank you very much for this. It helps a lot to get intellisense for the whole WordPress core.

I would just like to add a tip for [VSCode Intelephense](https://github.com/bmewburn/vscode-intelephense) users. 

1. Since the stub file is around 2.8MB, we need to tweak the settings and add `"intelephense.file.maxSize": 3000000`, which will parse and index files upto around 3MB.
2. Now do a `Intelephense: Clear Cache and Reload` and you will be good to go.

The log came up like this

```
[Info  - 15:33:16] Initialising
[Info  - 15:33:20] Initialised in 3922 ms
[Info  - 15:33:20] Intelephense 0.8.6
[Info  - 15:33:30] Indexing started.
[Info  - 15:34:08] Indexing ended | 3813 files | 38.206 s
```

38s is considerably fast given all the other dependencies.

**Comment by swashata** [comment]
Great. I have written a bit more elaborated steps here bmewburn/vscode-intelephense#113

**Comment by GiacoCorsiglia** [comment]
Thanks again—I've finally updated the README.
