### ISSUE TITLE
wp-includes/compat.php conflicts with PHP 7.3

### ISSUE THREAD

**Issue by szepeviktor** [GiacoCorsiglia/wordpress-stubs#13]
`->notPath('wp-includes/compat.php')`

@GiacoCorsiglia @localheinz Please reconsider removing it.

https://www.php.net/manual/en/function.is-countable.php

**Comment by Mte90** [comment]
I can confirm I have to do:
`php7.2 vendor/bin/phpstan analyze`

**Comment by localheinz** [comment]
@Mte90 @szepeviktor 

Just to clarify: would you like me to apply this patch?

```diff
diff --git a/finder.php b/finder.php
index c7518cf..7ac6bc1 100644
--- a/finder.php
+++ b/finder.php
@@ -4,6 +4,7 @@ return \StubsGenerator\Finder::create()
     ->in('wordpress')
     ->notPath('wp-admin/includes/noop.php')
     ->notPath('wp-content')
+    ->notPath('wp-includes/compat.php')
     ->notPath('wp-includes/spl-autoload-compat.php')
     ->sortByName()
 ;
```

**Comment by szepeviktor** [comment]
Yes, indeed.

**Comment by szepeviktor** [comment]
But then `is_countable()` will not be available in <7.3

**Comment by szepeviktor** [comment]
Maybe add symfony/polyfill-php73 as a dependency...

**Comment by szepeviktor** [comment]
@localheinz Could you release WP 5.2 versions?

**Comment by szepeviktor** [comment]
Fixed in a Composer script: https://github.com/szepeviktor/phpstan-wordpress/blob/master/src/Composer/FixWpStubs.php

**Comment by KeironLowe** [comment]
@szepeviktor how do you implement that script?

**Comment by szepeviktor** [comment]
@KeironLowe As a Composer script https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/composer.json#L19-L22

**Comment by KeironLowe** [comment]
@szepeviktor Thank you, was more which events I wasn't sure about!

**Comment by szepeviktor** [comment]
Starting WordPress stubs without compat code: https://github.com/php-stubs/wordpress-stubs
See details there.

**Comment by szepeviktor** [comment]
My fork's `finder.php` just got better: https://github.com/php-stubs/wordpress-stubs/blob/master/finder.php - stubs got shorter!
